[package]
name = "example"
version = "0.0.1"
edition = "2021"

[dependencies]
variant-map = { path = "../crates/variant-map", features = ["derive", "macros"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0.105" }